ALTER TABLE job.aka_name ADD PRIMARY KEY (id);
ALTER TABLE job.aka_title ADD PRIMARY KEY (id);
ALTER TABLE job.cast_info ADD PRIMARY KEY (id);
ALTER TABLE job.char_name ADD PRIMARY KEY (id);
ALTER TABLE job.comp_cast_type ADD PRIMARY KEY (id);
ALTER TABLE job.company_name ADD PRIMARY KEY (id);
ALTER TABLE job.company_type ADD PRIMARY KEY (id);
ALTER TABLE job.complete_cast ADD PRIMARY KEY (id);
ALTER TABLE job.info_type ADD PRIMARY KEY (id);
ALTER TABLE job.keyword ADD PRIMARY KEY (id);
ALTER TABLE job.kind_type ADD PRIMARY KEY (id);
ALTER TABLE job.link_type ADD PRIMARY KEY (id);
ALTER TABLE job.movie_companies ADD PRIMARY KEY (id);
ALTER TABLE job.movie_info ADD PRIMARY KEY (id);
ALTER TABLE job.movie_info_idx ADD PRIMARY KEY (id);
ALTER TABLE job.movie_keyword ADD PRIMARY KEY (id);
ALTER TABLE job.movie_link ADD PRIMARY KEY (id);
ALTER TABLE job.name ADD PRIMARY KEY (id);
ALTER TABLE job.person_info ADD PRIMARY KEY (id);
ALTER TABLE job.role_type ADD PRIMARY KEY (id);
ALTER TABLE job.title ADD PRIMARY KEY (id);

ALTER TABLE job.aka_name ADD FOREIGN KEY (person_id) REFERENCES job.name (id);
ALTER TABLE job.aka_title ADD FOREIGN KEY (movie_id) REFERENCES job.title (id);
ALTER TABLE job.aka_title ADD FOREIGN KEY (kind_id) REFERENCES job.kind_type (id);
ALTER TABLE job.aka_title ADD FOREIGN KEY (episode_of_id) REFERENCES job.title (id);
ALTER TABLE job.cast_info ADD FOREIGN KEY (person_id) REFERENCES job.name (id);
ALTER TABLE job.cast_info ADD FOREIGN KEY (movie_id) REFERENCES job.title (id);
ALTER TABLE job.cast_info ADD FOREIGN KEY (person_role_id) REFERENCES job.char_name (id);
ALTER TABLE job.cast_info ADD FOREIGN KEY (role_id) REFERENCES job.role_type (id);
ALTER TABLE job.complete_cast ADD FOREIGN KEY (movie_id) REFERENCES job.title (id);
ALTER TABLE job.complete_cast ADD FOREIGN KEY (subject_id) REFERENCES job.comp_cast_type (id);
ALTER TABLE job.complete_cast ADD FOREIGN KEY (status_id) REFERENCES job.comp_cast_type (id);
ALTER TABLE job.movie_companies ADD FOREIGN KEY (movie_id) REFERENCES job.title (id);
ALTER TABLE job.movie_companies ADD FOREIGN KEY (company_id) REFERENCES job.company_name (id);
ALTER TABLE job.movie_companies ADD FOREIGN KEY (company_type_id) REFERENCES job.company_type (id);
ALTER TABLE job.movie_info ADD FOREIGN KEY (movie_id) REFERENCES job.title (id);
ALTER TABLE job.movie_info ADD FOREIGN KEY (info_type_id) REFERENCES job.info_type (id);
ALTER TABLE job.movie_info_idx ADD FOREIGN KEY (movie_id) REFERENCES job.title (id);
ALTER TABLE job.movie_info_idx ADD FOREIGN KEY (info_type_id) REFERENCES job.info_type (id);
ALTER TABLE job.movie_keyword ADD FOREIGN KEY (movie_id) REFERENCES job.title (id);
ALTER TABLE job.movie_keyword ADD FOREIGN KEY (keyword_id) REFERENCES job.keyword (id);
ALTER TABLE job.movie_link ADD FOREIGN KEY (movie_id) REFERENCES job.title (id);
ALTER TABLE job.movie_link ADD FOREIGN KEY (linked_movie_id) REFERENCES job.title (id);
ALTER TABLE job.movie_link ADD FOREIGN KEY (link_type_id) REFERENCES job.link_type (id);
ALTER TABLE job.person_info ADD FOREIGN KEY (person_id) REFERENCES job.name (id);
ALTER TABLE job.person_info ADD FOREIGN KEY (info_type_id) REFERENCES job.info_type (id);
ALTER TABLE job.title ADD FOREIGN KEY (kind_id) REFERENCES job.kind_type (id);
ALTER TABLE job.title ADD FOREIGN KEY (episode_of_id) REFERENCES job.title (id);
