/* Public BI Generico 36 */
SELECT CAST(EXTRACT(YEAR FROM "Generico_5"."FECHA") AS BIGINT) AS "yr:FECHA:ok" FROM publicbi."Generico_5" WHERE ((CAST(EXTRACT(YEAR FROM "Generico_5"."FECHA") AS BIGINT) >= 2010) AND (CAST(EXTRACT(YEAR FROM "Generico_5"."FECHA") AS BIGINT) <= 2015) AND ("Generico_5"."Anunciante" IN ('BANTRAB/TODOTICKET', 'TODOTICKET', 'TODOTICKET.COM'))) GROUP BY "yr:FECHA:ok";
