CREATE TABLE tpcds_sf1.call_center (
    cc_call_center_sk BIGINT NOT NULL,
    cc_call_center_id VARCHAR NOT NULL,
    cc_rec_start_date DATE NULL,
    cc_rec_end_date DATE NULL,
    cc_closed_date_sk BIGINT NULL,
    cc_open_date_sk BIGINT NULL,
    cc_name VARCHAR NULL,
    cc_class VARCHAR NULL,
    cc_employees BIGINT NULL,
    cc_sq_ft BIGINT NULL,
    cc_hours VARCHAR NULL,
    cc_manager VARCHAR NULL,
    cc_mkt_id BIGINT NULL,
    cc_mkt_class VARCHAR NULL,
    cc_mkt_desc VARCHAR NULL,
    cc_market_manager VARCHAR NULL,
    cc_division BIGINT NULL,
    cc_division_name VARCHAR NULL,
    cc_company BIGINT NULL,
    cc_company_name VARCHAR NULL,
    cc_street_number VARCHAR NULL,
    cc_street_name VARCHAR NULL,
    cc_street_type VARCHAR NULL,
    cc_suite_number VARCHAR NULL,
    cc_city VARCHAR NULL,
    cc_county VARCHAR NULL,
    cc_state VARCHAR NULL,
    cc_zip VARCHAR NULL,
    cc_country VARCHAR NULL,
    cc_gmt_offset DECIMAL(5,2) NULL,
    cc_tax_percentage DECIMAL(5,2) NULL
);
