CREATE TABLE tpcds_sf1.catalog_sales (
    cs_sold_date_sk BIGINT NULL,
    cs_sold_time_sk BIGINT NULL,
    cs_ship_date_sk BIGINT NULL,
    cs_bill_customer_sk BIGINT NULL,
    cs_bill_cdemo_sk BIGINT NULL,
    cs_bill_hdemo_sk BIGINT NULL,
    cs_bill_addr_sk BIGINT NULL,
    cs_ship_customer_sk BIGINT NULL,
    cs_ship_cdemo_sk BIGINT NULL,
    cs_ship_hdemo_sk BIGINT NULL,
    cs_ship_addr_sk BIGINT NULL,
    cs_call_center_sk BIGINT NULL,
    cs_catalog_page_sk BIGINT NULL,
    cs_ship_mode_sk BIGINT NULL,
    cs_warehouse_sk BIGINT NULL,
    cs_item_sk BIGINT NOT NULL,
    cs_promo_sk BIGINT NULL,
    cs_order_number BIGINT NOT NULL,
    cs_quantity BIGINT NULL,
    cs_wholesale_cost DECIMAL(7,2) NULL,
    cs_list_price DECIMAL(7,2) NULL,
    cs_sales_price DECIMAL(7,2) NULL,
    cs_ext_discount_amt DECIMAL(7,2) NULL,
    cs_ext_sales_price DECIMAL(7,2) NULL,
    cs_ext_wholesale_cost DECIMAL(7,2) NULL,
    cs_ext_list_price DECIMAL(7,2) NULL,
    cs_ext_tax DECIMAL(7,2) NULL,
    cs_coupon_amt DECIMAL(7,2) NULL,
    cs_ext_ship_cost DECIMAL(7,2) NULL,
    cs_net_paid DECIMAL(7,2) NULL,
    cs_net_paid_inc_tax DECIMAL(7,2) NULL,
    cs_net_paid_inc_ship DECIMAL(7,2) NULL,
    cs_net_paid_inc_ship_tax DECIMAL(7,2) NULL,
    cs_net_profit DECIMAL(7,2) NULL
);
