CREATE TABLE tpcds_sf1.catalog_returns (
    cr_returned_date_sk BIGINT NULL,
    cr_returned_time_sk BIGINT NULL,
    cr_item_sk BIGINT NOT NULL,
    cr_refunded_customer_sk BIGINT NULL,
    cr_refunded_cdemo_sk BIGINT NULL,
    cr_refunded_hdemo_sk BIGINT NULL,
    cr_refunded_addr_sk BIGINT NULL,
    cr_returning_customer_sk BIGINT NULL,
    cr_returning_cdemo_sk BIGINT NULL,
    cr_returning_hdemo_sk BIGINT NULL,
    cr_returning_addr_sk BIGINT NULL,
    cr_call_center_sk BIGINT NULL,
    cr_catalog_page_sk BIGINT NULL,
    cr_ship_mode_sk BIGINT NULL,
    cr_warehouse_sk BIGINT NULL,
    cr_reason_sk BIGINT NULL,
    cr_order_number BIGINT NOT NULL,
    cr_return_quantity BIGINT NULL,
    cr_return_amount DECIMAL(7,2) NULL,
    cr_return_tax DECIMAL(7,2) NULL,
    cr_return_amt_inc_tax DECIMAL(7,2) NULL,
    cr_fee DECIMAL(7,2) NULL,
    cr_return_ship_cost DECIMAL(7,2) NULL,
    cr_refunded_cash DECIMAL(7,2) NULL,
    cr_reversed_charge DECIMAL(7,2) NULL,
    cr_store_credit DECIMAL(7,2) NULL,
    cr_net_loss DECIMAL(7,2) NULL
);
