CREATE TABLE tpcds_sf1.item (
    i_item_sk BIGINT NOT NULL,
    i_item_id VARCHAR NOT NULL,
    i_rec_start_date DATE NULL,
    i_rec_end_date DATE NULL,
    i_item_desc VARCHAR NULL,
    i_current_price DECIMAL(7,2) NULL,
    i_wholesale_cost DECIMAL(7,2) NULL,
    i_brand_id BIGINT NULL,
    i_brand VARCHAR NULL,
    i_class_id BIGINT NULL,
    i_class VARCHAR NULL,
    i_category_id BIGINT NULL,
    i_category VARCHAR NULL,
    i_manufact_id BIGINT NULL,
    i_manufact VARCHAR NULL,
    i_size VARCHAR NULL,
    i_formulation VARCHAR NULL,
    i_color VARCHAR NULL,
    i_units VARCHAR NULL,
    i_container VARCHAR NULL,
    i_manager_id BIGINT NULL,
    i_product_name VARCHAR NULL
);
