ALTER TABLE tpcds_sf1.customer_address ADD PRIMARY KEY (ca_address_sk);
ALTER TABLE tpcds_sf1.customer_demographics ADD PRIMARY KEY (cd_demo_sk);
ALTER TABLE tpcds_sf1.date_dim ADD PRIMARY KEY (d_date_sk);
ALTER TABLE tpcds_sf1.warehouse ADD PRIMARY KEY (w_warehouse_sk);
ALTER TABLE tpcds_sf1.ship_mode ADD PRIMARY KEY (sm_ship_mode_sk);
ALTER TABLE tpcds_sf1.time_dim ADD PRIMARY KEY (t_time_sk);
ALTER TABLE tpcds_sf1.reason ADD PRIMARY KEY (r_reason_sk);
ALTER TABLE tpcds_sf1.income_band ADD PRIMARY KEY (ib_income_band_sk);
ALTER TABLE tpcds_sf1.item ADD PRIMARY KEY (i_item_sk);
ALTER TABLE tpcds_sf1.store ADD PRIMARY KEY (s_store_sk);
ALTER TABLE tpcds_sf1.call_center ADD PRIMARY KEY (cc_call_center_sk);
ALTER TABLE tpcds_sf1.customer ADD PRIMARY KEY (c_customer_sk);
ALTER TABLE tpcds_sf1.web_site ADD PRIMARY KEY (web_site_sk);
ALTER TABLE tpcds_sf1.store_returns ADD PRIMARY KEY (sr_item_sk, sr_ticket_number);
ALTER TABLE tpcds_sf1.household_demographics ADD PRIMARY KEY (hd_demo_sk);
ALTER TABLE tpcds_sf1.web_page ADD PRIMARY KEY (wp_web_page_sk);
ALTER TABLE tpcds_sf1.promotion ADD PRIMARY KEY (p_promo_sk);
ALTER TABLE tpcds_sf1.catalog_page ADD PRIMARY KEY (cp_catalog_page_sk);
ALTER TABLE tpcds_sf1.inventory ADD PRIMARY KEY (inv_date_sk, inv_item_sk, inv_warehouse_sk);
ALTER TABLE tpcds_sf1.catalog_returns ADD PRIMARY KEY (cr_item_sk, cr_order_number);
ALTER TABLE tpcds_sf1.web_returns ADD PRIMARY KEY (wr_item_sk, wr_order_number);
ALTER TABLE tpcds_sf1.web_sales ADD PRIMARY KEY (ws_item_sk, ws_order_number);
ALTER TABLE tpcds_sf1.catalog_sales ADD PRIMARY KEY (cs_item_sk, cs_order_number);
ALTER TABLE tpcds_sf1.store_sales ADD PRIMARY KEY (ss_item_sk, ss_ticket_number);

ALTER TABLE tpcds_sf1.call_center ADD FOREIGN KEY (cc_closed_date_sk) REFERENCES tpcds_sf1.date_dim (d_date_sk);
ALTER TABLE tpcds_sf1.call_center ADD FOREIGN KEY (cc_open_date_sk) REFERENCES tpcds_sf1.date_dim (d_date_sk);
ALTER TABLE tpcds_sf1.catalog_page ADD FOREIGN KEY (cp_end_date_sk) REFERENCES tpcds_sf1.date_dim (d_date_sk);
ALTER TABLE tpcds_sf1.catalog_page ADD FOREIGN KEY (cp_start_date_sk) REFERENCES tpcds_sf1.date_dim (d_date_sk);
ALTER TABLE tpcds_sf1.catalog_returns ADD FOREIGN KEY (cr_call_center_sk) REFERENCES tpcds_sf1.call_center (cc_call_center_sk);
ALTER TABLE tpcds_sf1.catalog_returns ADD FOREIGN KEY (cr_catalog_page_sk) REFERENCES tpcds_sf1.catalog_page (cp_catalog_page_sk);
ALTER TABLE tpcds_sf1.catalog_returns ADD FOREIGN KEY (cr_item_sk) REFERENCES tpcds_sf1.item (i_item_sk);
ALTER TABLE tpcds_sf1.catalog_returns ADD FOREIGN KEY (cr_reason_sk) REFERENCES tpcds_sf1.reason (r_reason_sk);
ALTER TABLE tpcds_sf1.catalog_returns ADD FOREIGN KEY (cr_refunded_addr_sk) REFERENCES tpcds_sf1.customer_address (ca_address_sk);
ALTER TABLE tpcds_sf1.catalog_returns ADD FOREIGN KEY (cr_refunded_cdemo_sk) REFERENCES tpcds_sf1.customer_demographics (cd_demo_sk);
ALTER TABLE tpcds_sf1.catalog_returns ADD FOREIGN KEY (cr_refunded_customer_sk) REFERENCES tpcds_sf1.customer (c_customer_sk);
ALTER TABLE tpcds_sf1.catalog_returns ADD FOREIGN KEY (cr_refunded_hdemo_sk) REFERENCES tpcds_sf1.household_demographics (hd_demo_sk);
ALTER TABLE tpcds_sf1.catalog_returns ADD FOREIGN KEY (cr_returned_date_sk) REFERENCES tpcds_sf1.date_dim (d_date_sk);
ALTER TABLE tpcds_sf1.catalog_returns ADD FOREIGN KEY (cr_returned_time_sk) REFERENCES tpcds_sf1.time_dim (t_time_sk);
ALTER TABLE tpcds_sf1.catalog_returns ADD FOREIGN KEY (cr_returning_addr_sk) REFERENCES tpcds_sf1.customer_address (ca_address_sk);
ALTER TABLE tpcds_sf1.catalog_returns ADD FOREIGN KEY (cr_returning_cdemo_sk) REFERENCES tpcds_sf1.customer_demographics (cd_demo_sk);
ALTER TABLE tpcds_sf1.catalog_returns ADD FOREIGN KEY (cr_returning_customer_sk) REFERENCES tpcds_sf1.customer (c_customer_sk);
ALTER TABLE tpcds_sf1.catalog_returns ADD FOREIGN KEY (cr_returning_hdemo_sk) REFERENCES tpcds_sf1.household_demographics (hd_demo_sk);
ALTER TABLE tpcds_sf1.catalog_returns ADD FOREIGN KEY (cr_ship_mode_sk) REFERENCES tpcds_sf1.ship_mode (sm_ship_mode_sk);
ALTER TABLE tpcds_sf1.catalog_returns ADD FOREIGN KEY (cr_warehouse_sk) REFERENCES tpcds_sf1.warehouse (w_warehouse_sk);
ALTER TABLE tpcds_sf1.catalog_sales ADD FOREIGN KEY (cs_bill_addr_sk) REFERENCES tpcds_sf1.customer_address (ca_address_sk);
ALTER TABLE tpcds_sf1.catalog_sales ADD FOREIGN KEY (cs_bill_cdemo_sk) REFERENCES tpcds_sf1.customer_demographics (cd_demo_sk);
ALTER TABLE tpcds_sf1.catalog_sales ADD FOREIGN KEY (cs_bill_customer_sk) REFERENCES tpcds_sf1.customer (c_customer_sk);
ALTER TABLE tpcds_sf1.catalog_sales ADD FOREIGN KEY (cs_bill_hdemo_sk) REFERENCES tpcds_sf1.household_demographics (hd_demo_sk);
ALTER TABLE tpcds_sf1.catalog_sales ADD FOREIGN KEY (cs_call_center_sk) REFERENCES tpcds_sf1.call_center (cc_call_center_sk);
ALTER TABLE tpcds_sf1.catalog_sales ADD FOREIGN KEY (cs_catalog_page_sk) REFERENCES tpcds_sf1.catalog_page (cp_catalog_page_sk);
ALTER TABLE tpcds_sf1.catalog_sales ADD FOREIGN KEY (cs_item_sk) REFERENCES tpcds_sf1.item (i_item_sk);
ALTER TABLE tpcds_sf1.catalog_sales ADD FOREIGN KEY (cs_promo_sk) REFERENCES tpcds_sf1.promotion (p_promo_sk);
ALTER TABLE tpcds_sf1.catalog_sales ADD FOREIGN KEY (cs_ship_addr_sk) REFERENCES tpcds_sf1.customer_address (ca_address_sk);
ALTER TABLE tpcds_sf1.catalog_sales ADD FOREIGN KEY (cs_ship_cdemo_sk) REFERENCES tpcds_sf1.customer_demographics (cd_demo_sk);
ALTER TABLE tpcds_sf1.catalog_sales ADD FOREIGN KEY (cs_ship_customer_sk) REFERENCES tpcds_sf1.customer (c_customer_sk);
ALTER TABLE tpcds_sf1.catalog_sales ADD FOREIGN KEY (cs_ship_date_sk) REFERENCES tpcds_sf1.date_dim (d_date_sk);
ALTER TABLE tpcds_sf1.catalog_sales ADD FOREIGN KEY (cs_ship_hdemo_sk) REFERENCES tpcds_sf1.household_demographics (hd_demo_sk);
ALTER TABLE tpcds_sf1.catalog_sales ADD FOREIGN KEY (cs_ship_mode_sk) REFERENCES tpcds_sf1.ship_mode (sm_ship_mode_sk);
ALTER TABLE tpcds_sf1.catalog_sales ADD FOREIGN KEY (cs_sold_date_sk) REFERENCES tpcds_sf1.date_dim (d_date_sk);
ALTER TABLE tpcds_sf1.catalog_sales ADD FOREIGN KEY (cs_sold_time_sk) REFERENCES tpcds_sf1.time_dim (t_time_sk);
ALTER TABLE tpcds_sf1.catalog_sales ADD FOREIGN KEY (cs_warehouse_sk) REFERENCES tpcds_sf1.warehouse (w_warehouse_sk);
ALTER TABLE tpcds_sf1.customer ADD FOREIGN KEY (c_current_addr_sk) REFERENCES tpcds_sf1.customer_address (ca_address_sk);
ALTER TABLE tpcds_sf1.customer ADD FOREIGN KEY (c_current_cdemo_sk) REFERENCES tpcds_sf1.customer_demographics (cd_demo_sk);
ALTER TABLE tpcds_sf1.customer ADD FOREIGN KEY (c_current_hdemo_sk) REFERENCES tpcds_sf1.household_demographics (hd_demo_sk);
ALTER TABLE tpcds_sf1.customer ADD FOREIGN KEY (c_first_sales_date_sk) REFERENCES tpcds_sf1.date_dim (d_date_sk);
ALTER TABLE tpcds_sf1.customer ADD FOREIGN KEY (c_first_shipto_date_sk) REFERENCES tpcds_sf1.date_dim (d_date_sk);
ALTER TABLE tpcds_sf1.household_demographics ADD FOREIGN KEY (hd_income_band_sk) REFERENCES tpcds_sf1.income_band (ib_income_band_sk);
ALTER TABLE tpcds_sf1.inventory ADD FOREIGN KEY (inv_date_sk) REFERENCES tpcds_sf1.date_dim (d_date_sk);
ALTER TABLE tpcds_sf1.inventory ADD FOREIGN KEY (inv_item_sk) REFERENCES tpcds_sf1.item (i_item_sk);
ALTER TABLE tpcds_sf1.inventory ADD FOREIGN KEY (inv_warehouse_sk) REFERENCES tpcds_sf1.warehouse (w_warehouse_sk);
ALTER TABLE tpcds_sf1.promotion ADD FOREIGN KEY (p_end_date_sk) REFERENCES tpcds_sf1.date_dim (d_date_sk);
ALTER TABLE tpcds_sf1.promotion ADD FOREIGN KEY (p_item_sk) REFERENCES tpcds_sf1.item (i_item_sk);
ALTER TABLE tpcds_sf1.promotion ADD FOREIGN KEY (p_start_date_sk) REFERENCES tpcds_sf1.date_dim (d_date_sk);
ALTER TABLE tpcds_sf1.store ADD FOREIGN KEY (s_closed_date_sk) REFERENCES tpcds_sf1.date_dim (d_date_sk);
ALTER TABLE tpcds_sf1.store_returns ADD FOREIGN KEY (sr_addr_sk) REFERENCES tpcds_sf1.customer_address (ca_address_sk);
ALTER TABLE tpcds_sf1.store_returns ADD FOREIGN KEY (sr_cdemo_sk) REFERENCES tpcds_sf1.customer_demographics (cd_demo_sk);
ALTER TABLE tpcds_sf1.store_returns ADD FOREIGN KEY (sr_customer_sk) REFERENCES tpcds_sf1.customer (c_customer_sk);
ALTER TABLE tpcds_sf1.store_returns ADD FOREIGN KEY (sr_hdemo_sk) REFERENCES tpcds_sf1.household_demographics (hd_demo_sk);
ALTER TABLE tpcds_sf1.store_returns ADD FOREIGN KEY (sr_item_sk) REFERENCES tpcds_sf1.item (i_item_sk);
ALTER TABLE tpcds_sf1.store_returns ADD FOREIGN KEY (sr_reason_sk) REFERENCES tpcds_sf1.reason (r_reason_sk);
ALTER TABLE tpcds_sf1.store_returns ADD FOREIGN KEY (sr_returned_date_sk) REFERENCES tpcds_sf1.date_dim (d_date_sk);
ALTER TABLE tpcds_sf1.store_returns ADD FOREIGN KEY (sr_return_time_sk) REFERENCES tpcds_sf1.time_dim (t_time_sk);
ALTER TABLE tpcds_sf1.store_returns ADD FOREIGN KEY (sr_store_sk) REFERENCES tpcds_sf1.store (s_store_sk);
ALTER TABLE tpcds_sf1.store_sales ADD FOREIGN KEY (ss_addr_sk) REFERENCES tpcds_sf1.customer_address (ca_address_sk);
ALTER TABLE tpcds_sf1.store_sales ADD FOREIGN KEY (ss_cdemo_sk) REFERENCES tpcds_sf1.customer_demographics (cd_demo_sk);
ALTER TABLE tpcds_sf1.store_sales ADD FOREIGN KEY (ss_customer_sk) REFERENCES tpcds_sf1.customer (c_customer_sk);
ALTER TABLE tpcds_sf1.store_sales ADD FOREIGN KEY (ss_hdemo_sk) REFERENCES tpcds_sf1.household_demographics (hd_demo_sk);
ALTER TABLE tpcds_sf1.store_sales ADD FOREIGN KEY (ss_item_sk) REFERENCES tpcds_sf1.item (i_item_sk);
ALTER TABLE tpcds_sf1.store_sales ADD FOREIGN KEY (ss_promo_sk) REFERENCES tpcds_sf1.promotion (p_promo_sk);
ALTER TABLE tpcds_sf1.store_sales ADD FOREIGN KEY (ss_sold_date_sk) REFERENCES tpcds_sf1.date_dim (d_date_sk);
ALTER TABLE tpcds_sf1.store_sales ADD FOREIGN KEY (ss_sold_time_sk) REFERENCES tpcds_sf1.time_dim (t_time_sk);
ALTER TABLE tpcds_sf1.store_sales ADD FOREIGN KEY (ss_store_sk) REFERENCES tpcds_sf1.store (s_store_sk);
ALTER TABLE tpcds_sf1.web_page ADD FOREIGN KEY (wp_access_date_sk) REFERENCES tpcds_sf1.date_dim (d_date_sk);
ALTER TABLE tpcds_sf1.web_page ADD FOREIGN KEY (wp_creation_date_sk) REFERENCES tpcds_sf1.date_dim (d_date_sk);
ALTER TABLE tpcds_sf1.web_returns ADD FOREIGN KEY (wr_item_sk) REFERENCES tpcds_sf1.item (i_item_sk);
ALTER TABLE tpcds_sf1.web_returns ADD FOREIGN KEY (wr_reason_sk) REFERENCES tpcds_sf1.reason (r_reason_sk);
ALTER TABLE tpcds_sf1.web_returns ADD FOREIGN KEY (wr_refunded_addr_sk) REFERENCES tpcds_sf1.customer_address (ca_address_sk);
ALTER TABLE tpcds_sf1.web_returns ADD FOREIGN KEY (wr_refunded_cdemo_sk) REFERENCES tpcds_sf1.customer_demographics (cd_demo_sk);
ALTER TABLE tpcds_sf1.web_returns ADD FOREIGN KEY (wr_refunded_customer_sk) REFERENCES tpcds_sf1.customer (c_customer_sk);
ALTER TABLE tpcds_sf1.web_returns ADD FOREIGN KEY (wr_refunded_hdemo_sk) REFERENCES tpcds_sf1.household_demographics (hd_demo_sk);
ALTER TABLE tpcds_sf1.web_returns ADD FOREIGN KEY (wr_returned_date_sk) REFERENCES tpcds_sf1.date_dim (d_date_sk);
ALTER TABLE tpcds_sf1.web_returns ADD FOREIGN KEY (wr_returned_time_sk) REFERENCES tpcds_sf1.time_dim (t_time_sk);
ALTER TABLE tpcds_sf1.web_returns ADD FOREIGN KEY (wr_returning_addr_sk) REFERENCES tpcds_sf1.customer_address (ca_address_sk);
ALTER TABLE tpcds_sf1.web_returns ADD FOREIGN KEY (wr_returning_cdemo_sk) REFERENCES tpcds_sf1.customer_demographics (cd_demo_sk);
ALTER TABLE tpcds_sf1.web_returns ADD FOREIGN KEY (wr_returning_customer_sk) REFERENCES tpcds_sf1.customer (c_customer_sk);
ALTER TABLE tpcds_sf1.web_returns ADD FOREIGN KEY (wr_returning_hdemo_sk) REFERENCES tpcds_sf1.household_demographics (hd_demo_sk);
ALTER TABLE tpcds_sf1.web_returns ADD FOREIGN KEY (wr_web_page_sk) REFERENCES tpcds_sf1.web_page (wp_web_page_sk);
ALTER TABLE tpcds_sf1.web_sales ADD FOREIGN KEY (ws_bill_addr_sk) REFERENCES tpcds_sf1.customer_address (ca_address_sk);
ALTER TABLE tpcds_sf1.web_sales ADD FOREIGN KEY (ws_bill_cdemo_sk) REFERENCES tpcds_sf1.customer_demographics (cd_demo_sk);
ALTER TABLE tpcds_sf1.web_sales ADD FOREIGN KEY (ws_bill_customer_sk) REFERENCES tpcds_sf1.customer (c_customer_sk);
ALTER TABLE tpcds_sf1.web_sales ADD FOREIGN KEY (ws_bill_hdemo_sk) REFERENCES tpcds_sf1.household_demographics (hd_demo_sk);
ALTER TABLE tpcds_sf1.web_sales ADD FOREIGN KEY (ws_item_sk) REFERENCES tpcds_sf1.item (i_item_sk);
ALTER TABLE tpcds_sf1.web_sales ADD FOREIGN KEY (ws_promo_sk) REFERENCES tpcds_sf1.promotion (p_promo_sk);
ALTER TABLE tpcds_sf1.web_sales ADD FOREIGN KEY (ws_ship_addr_sk) REFERENCES tpcds_sf1.customer_address (ca_address_sk);
ALTER TABLE tpcds_sf1.web_sales ADD FOREIGN KEY (ws_ship_cdemo_sk) REFERENCES tpcds_sf1.customer_demographics (cd_demo_sk);
ALTER TABLE tpcds_sf1.web_sales ADD FOREIGN KEY (ws_ship_customer_sk) REFERENCES tpcds_sf1.customer (c_customer_sk);
ALTER TABLE tpcds_sf1.web_sales ADD FOREIGN KEY (ws_ship_date_sk) REFERENCES tpcds_sf1.date_dim (d_date_sk);
ALTER TABLE tpcds_sf1.web_sales ADD FOREIGN KEY (ws_ship_hdemo_sk) REFERENCES tpcds_sf1.household_demographics (hd_demo_sk);
ALTER TABLE tpcds_sf1.web_sales ADD FOREIGN KEY (ws_ship_mode_sk) REFERENCES tpcds_sf1.ship_mode (sm_ship_mode_sk);
ALTER TABLE tpcds_sf1.web_sales ADD FOREIGN KEY (ws_sold_date_sk) REFERENCES tpcds_sf1.date_dim (d_date_sk);
ALTER TABLE tpcds_sf1.web_sales ADD FOREIGN KEY (ws_sold_time_sk) REFERENCES tpcds_sf1.time_dim (t_time_sk);
ALTER TABLE tpcds_sf1.web_sales ADD FOREIGN KEY (ws_warehouse_sk) REFERENCES tpcds_sf1.warehouse (w_warehouse_sk);
ALTER TABLE tpcds_sf1.web_sales ADD FOREIGN KEY (ws_web_page_sk) REFERENCES tpcds_sf1.web_page (wp_web_page_sk);
ALTER TABLE tpcds_sf1.web_sales ADD FOREIGN KEY (ws_web_site_sk) REFERENCES tpcds_sf1.web_site (web_site_sk);
ALTER TABLE tpcds_sf1.web_site ADD FOREIGN KEY (web_close_date_sk) REFERENCES tpcds_sf1.date_dim (d_date_sk);
ALTER TABLE tpcds_sf1.web_site ADD FOREIGN KEY (web_open_date_sk) REFERENCES tpcds_sf1.date_dim (d_date_sk);
