CREATE TABLE tpcds_sf1.store (
    s_store_sk BIGINT NOT NULL,
    s_store_id VARCHAR NOT NULL,
    s_rec_start_date DATE NULL,
    s_rec_end_date DATE NULL,
    s_closed_date_sk BIGINT NULL,
    s_store_name VARCHAR NULL,
    s_number_employees BIGINT NULL,
    s_floor_space BIGINT NULL,
    s_hours VARCHAR NULL,
    s_manager VARCHAR NULL,
    s_market_id BIGINT NULL,
    s_geography_class VARCHAR NULL,
    s_market_desc VARCHAR NULL,
    s_market_manager VARCHAR NULL,
    s_division_id BIGINT NULL,
    s_division_name VARCHAR NULL,
    s_company_id BIGINT NULL,
    s_company_name VARCHAR NULL,
    s_street_number VARCHAR NULL,
    s_street_name VARCHAR NULL,
    s_street_type VARCHAR NULL,
    s_suite_number VARCHAR NULL,
    s_city VARCHAR NULL,
    s_county VARCHAR NULL,
    s_state VARCHAR NULL,
    s_zip VARCHAR NULL,
    s_country VARCHAR NULL,
    s_gmt_offset DECIMAL(5,2) NULL,
    s_tax_percentage DECIMAL(5,2) NULL
);
