CREATE TABLE tpcds_sf1.store_sales (
    ss_sold_date_sk BIGINT NULL,
    ss_sold_time_sk BIGINT NULL,
    ss_item_sk BIGINT NOT NULL,
    ss_customer_sk BIGINT NULL,
    ss_cdemo_sk BIGINT NULL,
    ss_hdemo_sk BIGINT NULL,
    ss_addr_sk BIGINT NULL,
    ss_store_sk BIGINT NULL,
    ss_promo_sk BIGINT NULL,
    ss_ticket_number BIGINT NOT NULL,
    ss_quantity BIGINT NULL,
    ss_wholesale_cost DECIMAL(7,2) NULL,
    ss_list_price DECIMAL(7,2) NULL,
    ss_sales_price DECIMAL(7,2) NULL,
    ss_ext_discount_amt DECIMAL(7,2) NULL,
    ss_ext_sales_price DECIMAL(7,2) NULL,
    ss_ext_wholesale_cost DECIMAL(7,2) NULL,
    ss_ext_list_price DECIMAL(7,2) NULL,
    ss_ext_tax DECIMAL(7,2) NULL,
    ss_coupon_amt DECIMAL(7,2) NULL,
    ss_net_paid DECIMAL(7,2) NULL,
    ss_net_paid_inc_tax DECIMAL(7,2) NULL,
    ss_net_profit DECIMAL(7,2) NULL
);
