CREATE TABLE tpcds_sf1.web_site (
    web_site_sk BIGINT NOT NULL,
    web_site_id VARCHAR NOT NULL,
    web_rec_start_date DATE NULL,
    web_rec_end_date DATE NULL,
    web_name VARCHAR NULL,
    web_open_date_sk BIGINT NULL,
    web_close_date_sk BIGINT NULL,
    web_class VARCHAR NULL,
    web_manager VARCHAR NULL,
    web_mkt_id BIGINT NULL,
    web_mkt_class VARCHAR NULL,
    web_mkt_desc VARCHAR NULL,
    web_market_manager VARCHAR NULL,
    web_company_id BIGINT NULL,
    web_company_name VARCHAR NULL,
    web_street_number VARCHAR NULL,
    web_street_name VARCHAR NULL,
    web_street_type VARCHAR NULL,
    web_suite_number VARCHAR NULL,
    web_city VARCHAR NULL,
    web_county VARCHAR NULL,
    web_state VARCHAR NULL,
    web_zip VARCHAR NULL,
    web_country VARCHAR NULL,
    web_gmt_offset DECIMAL(5,2) NULL,
    web_tax_percentage DECIMAL(5,2) NULL
);
