CREATE TABLE nyctaxi.fhvhv_tripdata (
    hvfhs_license_num VARCHAR NULL,
    dispatching_base_num VARCHAR NULL,
    originating_base_num VARCHAR NULL,
    request_datetime TIMESTAMP NULL,
    on_scene_datetime TIMESTAMP NULL,
    pickup_datetime TIMESTAMP NULL,
    dropoff_datetime TIMESTAMP NULL,
    pu_location_id INT NULL,
    do_location_id INT NULL,
    trip_miles DOUBLE NULL,
    trip_time BIGINT NULL,
    base_passenger_fare DOUBLE NULL,
    tolls DOUBLE NULL,
    bcf DOUBLE NULL,
    sales_tax DOUBLE NULL,
    congestion_surcharge DOUBLE NULL,
    airport_fee DOUBLE NULL,
    tips DOUBLE NULL,
    driver_pay DOUBLE NULL,
    shared_request_flag VARCHAR NULL,
    shared_match_flag VARCHAR NULL,
    access_a_ride_flag VARCHAR NULL,
    wav_request_flag VARCHAR NULL,
    wav_match_flag VARCHAR NULL,
    cbd_congestion_fee DOUBLE NULL
);
