CREATE TABLE nyctaxi.yellow_tripdata (
    vendor_id INT NULL,
    pickup_datetime TIMESTAMP NULL,
    dropoff_datetime TIMESTAMP NULL,
    passenger_count INT NULL,
    trip_distance DOUBLE NULL,
    rate_code_id INT NULL,
    store_and_fwd_flag VARCHAR NULL,
    pu_location_id INT NULL,
    do_location_id INT NULL,
    payment_type INT NULL,
    fare_amount DOUBLE NULL,
    extra DOUBLE NULL,
    mta_tax DOUBLE NULL,
    tip_amount DOUBLE NULL,
    tolls_amount DOUBLE NULL,
    improvement_surcharge DOUBLE NULL,
    total_amount DOUBLE NULL,
    congestion_surcharge DOUBLE NULL,
    airport_fee DOUBLE NULL,
    cbd_congestion_fee DOUBLE NULL,
    request_source VARCHAR NULL
);
