CREATE TABLE nyctaxi.yellow_tripdata_legacy (
    vendor VARCHAR NULL,
    pickup_datetime TIMESTAMP NULL,
    dropoff_datetime TIMESTAMP NULL,
    passenger_count INT NULL,
    trip_distance DOUBLE NULL,
    pickup_longitude DOUBLE NULL,
    pickup_latitude DOUBLE NULL,
    rate_code VARCHAR NULL,
    store_and_fwd_flag VARCHAR NULL,
    dropoff_longitude DOUBLE NULL,
    dropoff_latitude DOUBLE NULL,
    payment_type VARCHAR NULL,
    fare_amount DOUBLE NULL,
    surcharge DOUBLE NULL,
    mta_tax DOUBLE NULL,
    tip_amount DOUBLE NULL,
    tolls_amount DOUBLE NULL,
    total_amount DOUBLE NULL
);
