CREATE TABLE tpcds_sf1000.date_dim (
    d_date_sk BIGINT NOT NULL,
    d_date_id VARCHAR NOT NULL,
    d_date DATE NULL,
    d_month_seq BIGINT NULL,
    d_week_seq BIGINT NULL,
    d_quarter_seq BIGINT NULL,
    d_year BIGINT NULL,
    d_dow BIGINT NULL,
    d_moy BIGINT NULL,
    d_dom BIGINT NULL,
    d_qoy BIGINT NULL,
    d_fy_year BIGINT NULL,
    d_fy_quarter_seq BIGINT NULL,
    d_fy_week_seq BIGINT NULL,
    d_day_name VARCHAR NULL,
    d_quarter_name VARCHAR NULL,
    d_holiday VARCHAR NULL,
    d_weekend VARCHAR NULL,
    d_following_holiday VARCHAR NULL,
    d_first_dom BIGINT NULL,
    d_last_dom BIGINT NULL,
    d_same_day_ly BIGINT NULL,
    d_same_day_lq BIGINT NULL,
    d_current_day VARCHAR NULL,
    d_current_week VARCHAR NULL,
    d_current_month VARCHAR NULL,
    d_current_quarter VARCHAR NULL,
    d_current_year VARCHAR NULL
);
