CREATE TABLE tpcds_sf1000.web_returns (
    wr_returned_date_sk BIGINT NULL,
    wr_returned_time_sk BIGINT NULL,
    wr_item_sk BIGINT NOT NULL,
    wr_refunded_customer_sk BIGINT NULL,
    wr_refunded_cdemo_sk BIGINT NULL,
    wr_refunded_hdemo_sk BIGINT NULL,
    wr_refunded_addr_sk BIGINT NULL,
    wr_returning_customer_sk BIGINT NULL,
    wr_returning_cdemo_sk BIGINT NULL,
    wr_returning_hdemo_sk BIGINT NULL,
    wr_returning_addr_sk BIGINT NULL,
    wr_web_page_sk BIGINT NULL,
    wr_reason_sk BIGINT NULL,
    wr_order_number BIGINT NOT NULL,
    wr_return_quantity BIGINT NULL,
    wr_return_amt DECIMAL(7,2) NULL,
    wr_return_tax DECIMAL(7,2) NULL,
    wr_return_amt_inc_tax DECIMAL(7,2) NULL,
    wr_fee DECIMAL(7,2) NULL,
    wr_return_ship_cost DECIMAL(7,2) NULL,
    wr_refunded_cash DECIMAL(7,2) NULL,
    wr_reversed_charge DECIMAL(7,2) NULL,
    wr_account_credit DECIMAL(7,2) NULL,
    wr_net_loss DECIMAL(7,2) NULL
);
