CREATE TABLE tpcds_sf1000.web_sales (
    ws_sold_date_sk BIGINT NULL,
    ws_sold_time_sk BIGINT NULL,
    ws_ship_date_sk BIGINT NULL,
    ws_item_sk BIGINT NOT NULL,
    ws_bill_customer_sk BIGINT NULL,
    ws_bill_cdemo_sk BIGINT NULL,
    ws_bill_hdemo_sk BIGINT NULL,
    ws_bill_addr_sk BIGINT NULL,
    ws_ship_customer_sk BIGINT NULL,
    ws_ship_cdemo_sk BIGINT NULL,
    ws_ship_hdemo_sk BIGINT NULL,
    ws_ship_addr_sk BIGINT NULL,
    ws_web_page_sk BIGINT NULL,
    ws_web_site_sk BIGINT NULL,
    ws_ship_mode_sk BIGINT NULL,
    ws_warehouse_sk BIGINT NULL,
    ws_promo_sk BIGINT NULL,
    ws_order_number BIGINT NOT NULL,
    ws_quantity BIGINT NULL,
    ws_wholesale_cost DECIMAL(7,2) NULL,
    ws_list_price DECIMAL(7,2) NULL,
    ws_sales_price DECIMAL(7,2) NULL,
    ws_ext_discount_amt DECIMAL(7,2) NULL,
    ws_ext_sales_price DECIMAL(7,2) NULL,
    ws_ext_wholesale_cost DECIMAL(7,2) NULL,
    ws_ext_list_price DECIMAL(7,2) NULL,
    ws_ext_tax DECIMAL(7,2) NULL,
    ws_coupon_amt DECIMAL(7,2) NULL,
    ws_ext_ship_cost DECIMAL(7,2) NULL,
    ws_net_paid DECIMAL(7,2) NULL,
    ws_net_paid_inc_tax DECIMAL(7,2) NULL,
    ws_net_paid_inc_ship DECIMAL(7,2) NULL,
    ws_net_paid_inc_ship_tax DECIMAL(7,2) NULL,
    ws_net_profit DECIMAL(7,2) NULL
);
