CREATE TABLE publicbi."CityMaxCapita_1" (
    "City/Admin" VARCHAR NULL,
    "City/State" VARCHAR NULL,
    "City" VARCHAR NULL,
    "Created Date/Time" DOUBLE NOT NULL,
    "Date Joined" DECIMAL(15,10) NOT NULL,
    "FF Ratio" DECIMAL(6,1) NOT NULL,
    "Favorites" INT NOT NULL,
    "First Link in Tweet" VARCHAR NULL,
    "Followers" INT NOT NULL,
    "Following" INT NOT NULL,
    "Gender" VARCHAR NOT NULL,
    "Influencer?" INT NOT NULL,
    "Keyword" VARCHAR NOT NULL,
    "LPF" DOUBLE NOT NULL,
    "Language" VARCHAR NOT NULL,
    "Lat" DECIMAL(10,8) NULL,
    "Listed Number" INT NULL,
    "Long Domain" VARCHAR NULL,
    "Long" DECIMAL(11,8) NULL,
    "Number of Records" INT NOT NULL,
    "Region" VARCHAR NULL,
    "Short Domain" VARCHAR NULL,
    "State/Country" VARCHAR NULL,
    "State" VARCHAR NULL,
    "Tweet Text" VARCHAR NOT NULL,
    "Tweets" INT NOT NULL,
    "Twitter Client" VARCHAR NULL,
    "User Bio" VARCHAR NULL,
    "User Loc" VARCHAR NULL,
    "Username 1" VARCHAR NULL,
    "Username" VARCHAR NOT NULL
);
