CREATE TABLE publicbi."CommonGovernment_5" (
    "Number of Records" INT NOT NULL,
    a_aid_acontid_agencyid VARCHAR NOT NULL,
    a_aid_acontid_piid VARCHAR NOT NULL,
    ag_name VARCHAR NOT NULL,
    agency_code VARCHAR NOT NULL,
    ase_rowid INT NOT NULL,
    award_type VARCHAR NOT NULL,
    award_type_code VARCHAR NOT NULL,
    award_type_key INT NOT NULL,
    baseandalloptionsvalue DOUBLE NOT NULL,
    baseandexercisedoptionsvalue DOUBLE NOT NULL,
    bureau_code VARCHAR NOT NULL,
    bureau_name VARCHAR NOT NULL,
    cd_contactiontype VARCHAR NULL,
    co_name VARCHAR NULL,
    co_state VARCHAR NULL,
    code VARCHAR NOT NULL,
    contract_num VARCHAR NULL,
    contract_signeddate VARCHAR NOT NULL,
    contractingofficeagencyid VARCHAR NOT NULL,
    count_fetched INT NOT NULL,
    count_total INT NOT NULL,
    description VARCHAR NOT NULL,
    fk_epa_des_prod INT NULL,
    fk_rec_mat INT NULL,
    ftsdollar DOUBLE NOT NULL,
    funding_agency VARCHAR NULL,
    funding_agency_key INT NOT NULL,
    funding_agency_name VARCHAR NOT NULL,
    gsadollar DOUBLE NOT NULL,
    gsaotherdollar DOUBLE NOT NULL,
    gwacs DOUBLE NOT NULL,
    level1_category VARCHAR NOT NULL,
    level2_category VARCHAR NOT NULL,
    naics_code VARCHAR NOT NULL,
    naics_name VARCHAR NOT NULL,
    nongsadollar DOUBLE NOT NULL,
    obligatedamount DOUBLE NOT NULL,
    obligatedamount_1 DECIMAL(1,0) NULL,
    pbsdollar DOUBLE NOT NULL,
    primary_contract_piid VARCHAR NOT NULL,
    prod_or_serv_code VARCHAR NOT NULL,
    prod_or_serv_code_desc VARCHAR NULL,
    psc_code VARCHAR NOT NULL,
    psc_code_description VARCHAR NOT NULL,
    psc_key INT NOT NULL,
    quarter VARCHAR NOT NULL,
    refidvid_agencyid VARCHAR NOT NULL,
    refidvid_piid VARCHAR NULL,
    short_name VARCHAR NOT NULL,
    signeddate VARCHAR NOT NULL,
    vend_contoffbussizedeterm VARCHAR NOT NULL,
    vend_dunsnumber VARCHAR NOT NULL,
    vend_vendorname VARCHAR NULL,
    whocanuse VARCHAR NULL,
    year VARCHAR NOT NULL
);
