CREATE TABLE publicbi."Corporations_1" (
    "Id1" INT NOT NULL,
    "Number of Records" INT NOT NULL,
    angelco_account VARCHAR NULL,
    business_model VARCHAR NULL,
    city VARCHAR NULL,
    continent VARCHAR NULL,
    country VARCHAR NULL,
    crunchbase_account VARCHAR NULL,
    facebook_account VARCHAR NULL,
    financing_stage VARCHAR NULL,
    founding_date VARCHAR NULL,
    id INT NOT NULL,
    industries VARCHAR NULL,
    keywords VARCHAR NULL,
    last_funding_date VARCHAR NULL,
    linkedin_account VARCHAR NULL,
    location VARCHAR NULL,
    long_description VARCHAR NULL,
    name VARCHAR NULL,
    num_employees INT NOT NULL,
    region VARCHAR NULL,
    score INT NOT NULL,
    short_descriptiion VARCHAR NULL,
    stage VARCHAR NULL,
    total_funding INT NOT NULL,
    twitter_account VARCHAR NULL,
    website VARCHAR NULL
);
