CREATE TABLE publicbi."Generico_4" (
    "Anunciante" VARCHAR NULL,
    "Aviso" VARCHAR NULL,
    "A�o" INT NOT NULL,
    "Cadena" VARCHAR NULL,
    "Categoria" VARCHAR NOT NULL,
    "Circulacion" VARCHAR NULL,
    "Codigo" INT NOT NULL,
    "Cols" INT NOT NULL,
    "Concatenar 1" VARCHAR NULL,
    "Concatenar 2" VARCHAR NULL,
    "Corte" INT NULL,
    "De_Npags" INT NULL,
    "Dia_Semana" INT NOT NULL,
    "Disco" INT NULL,
    "Duracion" INT NULL,
    "Est" VARCHAR NULL,
    "FECHA" DATE NOT NULL,
    "Franja" VARCHAR NULL,
    "Genero" VARCHAR NULL,
    "Holding" VARCHAR NOT NULL,
    "Hora_Pagina" INT NULL,
    "InversionQ" DOUBLE NOT NULL,
    "InversionUS" DOUBLE NOT NULL,
    "Marca" VARCHAR NOT NULL,
    "Medio" VARCHAR NOT NULL,
    "Mes" VARCHAR NOT NULL,
    "NumAnuncios" INT NOT NULL,
    "Number of Records" INT NOT NULL,
    "Plgs" INT NOT NULL,
    "Posicion_Edicion" INT NULL,
    "PrimeraLinea" VARCHAR NULL,
    "Producto" VARCHAR NOT NULL,
    "SEMANA" INT NULL,
    "Sector" VARCHAR NOT NULL,
    "Soporte" VARCHAR NULL,
    "Subsector" VARCHAR NOT NULL,
    "Unidad" VARCHAR NULL,
    "VER ANUNCIO" VARCHAR NULL,
    "Vehiculo" VARCHAR NOT NULL,
    extencion VARCHAR NULL,
    medio2 VARCHAR NULL,
    www1 VARCHAR NULL,
    www2 VARCHAR NULL
);
