CREATE TABLE publicbi."HashTags_1" (
    "Number of Records" INT NOT NULL,
    "demographic#gender" VARCHAR NULL,
    "interaction#author#avatar" VARCHAR NOT NULL,
    "interaction#author#id" DOUBLE NULL,
    "interaction#author#language" VARCHAR NOT NULL,
    "interaction#author#link" VARCHAR NOT NULL,
    "interaction#author#name" VARCHAR NULL,
    "interaction#author#username" VARCHAR NOT NULL,
    "interaction#content" VARCHAR NOT NULL,
    "interaction#created_at" VARCHAR NOT NULL,
    "interaction#geo#latitude" DECIMAL(11,9) NULL,
    "interaction#geo#longitude" DECIMAL(11,8) NULL,
    "interaction#hashtags" VARCHAR NULL,
    "interaction#id" VARCHAR NOT NULL,
    "interaction#link" VARCHAR NOT NULL,
    "interaction#mention_ids" VARCHAR NULL,
    "interaction#mentions" VARCHAR NULL,
    "interaction#received_at" DOUBLE NULL,
    "interaction#schema#version" INT NOT NULL,
    "interaction#source" VARCHAR NOT NULL,
    "interaction#type" VARCHAR NOT NULL,
    "twitter#created_at" VARCHAR NOT NULL,
    "twitter#display_urls" VARCHAR NULL,
    "twitter#domains" VARCHAR NULL,
    "twitter#filter_level" VARCHAR NOT NULL,
    "twitter#geo#latitude" DECIMAL(11,9) NULL,
    "twitter#geo#longitude" DECIMAL(11,8) NULL,
    "twitter#hashtags" VARCHAR NULL,
    "twitter#id" DOUBLE NOT NULL,
    "twitter#in_reply_to_screen_name" VARCHAR NULL,
    "twitter#in_reply_to_status_id" DOUBLE NULL,
    "twitter#in_reply_to_user_id" BIGINT NULL,
    "twitter#lang" VARCHAR NOT NULL,
    "twitter#links" VARCHAR NULL,
    "twitter#media" VARCHAR NULL,
    "twitter#mention_ids" VARCHAR NULL,
    "twitter#mentions" VARCHAR NULL,
    "twitter#place#country" VARCHAR NULL,
    "twitter#place#country_code" VARCHAR NULL,
    "twitter#place#full_name" VARCHAR NULL,
    "twitter#place#id" VARCHAR NULL,
    "twitter#place#name" VARCHAR NULL,
    "twitter#place#place_type" VARCHAR NULL,
    "twitter#place#url" VARCHAR NULL,
    "twitter#possibly_sensitive" VARCHAR NULL,
    "twitter#source" VARCHAR NOT NULL,
    "twitter#text" VARCHAR NOT NULL,
    "twitter#user#created_at" VARCHAR NOT NULL,
    "twitter#user#description" VARCHAR NULL,
    "twitter#user#favourites_count" INT NOT NULL,
    "twitter#user#followers_count" INT NOT NULL,
    "twitter#user#friends_count" INT NOT NULL,
    "twitter#user#geo_enabled" VARCHAR NOT NULL,
    "twitter#user#id" DOUBLE NULL,
    "twitter#user#id_str" DOUBLE NULL,
    "twitter#user#lang" VARCHAR NOT NULL,
    "twitter#user#listed_count" INT NOT NULL,
    "twitter#user#location" VARCHAR NULL,
    "twitter#user#name" VARCHAR NULL,
    "twitter#user#profile_image_url" VARCHAR NOT NULL,
    "twitter#user#profile_image_url_https" VARCHAR NOT NULL,
    "twitter#user#screen_name" VARCHAR NOT NULL,
    "twitter#user#statuses_count" INT NOT NULL,
    "twitter#user#time_zone" VARCHAR NULL,
    "twitter#user#url" VARCHAR NULL,
    "twitter#user#utc_offset" INT NULL,
    "twitter#user#verified" VARCHAR NOT NULL,
    "Contains: suburgatory (copy)" INT NOT NULL,
    "Contains: Castle (copy)" INT NOT NULL,
    "Contains: revenge (copy)" INT NOT NULL,
    "Contains: nashville (copy)" INT NOT NULL,
    "Contains: modernfamily (copy)" INT NOT NULL,
    "Contains: lastmanstanding (copy)" INT NOT NULL,
    "Contains: TheNeighbors (copy)" INT NOT NULL,
    "Contains: TheNeighbors (copy 3)" INT NOT NULL,
    "Contains: TheNeighbors (copy 2)" INT NOT NULL,
    "Contains: suburgatory (copy 2)" INT NOT NULL,
    "Contains: Scandal (copy)" INT NOT NULL,
    "Contains: Scandal (copy 3)" INT NOT NULL,
    "Contains: Scandal (copy 2)" INT NOT NULL,
    "Contains: RookieBlue (copy)" INT NOT NULL,
    "Contains: RookieBlue (copy 6)" INT NOT NULL,
    "Contains: RookieBlue (copy 5)" INT NOT NULL,
    "Contains: RookieBlue (copy 4)" INT NOT NULL,
    "Contains: RookieBlue (copy 3)" INT NOT NULL,
    "Contains: RookieBlue (copy 2)" INT NOT NULL,
    "Contains: OnceUponATime (copy)" INT NOT NULL,
    "Contains: Motive (copy)" INT NOT NULL,
    "Contains: Motive (copy 2)" INT NOT NULL,
    "Contains: KillerWomen (copy)" INT NOT NULL,
    "Contains: KillerWomen (copy 2)" INT NOT NULL,
    "Contains: GreysAnatomy (copy)" INT NOT NULL,
    "Contains: GreysAnatomy (copy 2)" INT NOT NULL,
    "Calculation_6220303224029615" INT NOT NULL,
    "Contains: Castle (copy 2)" INT NOT NULL,
    "Contains: AgentsofSHIELD (copy)" INT NOT NULL,
    "Contains: AFV (copy)" INT NOT NULL,
    "Contains: AFV (copy 2)" INT NOT NULL,
    "Contains: ABC2020 (copy)" INT NOT NULL,
    "Calculation_6610227171140491" TIMESTAMP NOT NULL,
    "Contains: TheMiddle (copy)" INT NOT NULL
);
