CREATE TABLE publicbi."Hatred_1" (
    "City" VARCHAR NULL,
    "Client" VARCHAR NOT NULL,
    "Created Date" DOUBLE NOT NULL,
    "F26" VARCHAR NULL,
    "F27" VARCHAR NULL,
    "F28" VARCHAR NULL,
    "FF Ratio" DOUBLE NOT NULL,
    "Favorites" INT NOT NULL,
    "Followers" INT NOT NULL,
    "Following" INT NOT NULL,
    "Gender" VARCHAR NOT NULL,
    "Influencer?" INT NOT NULL,
    "Joined" DECIMAL(15,10) NOT NULL,
    "Keyword" VARCHAR NOT NULL,
    "LPF" DECIMAL(7,2) NOT NULL,
    "Language" VARCHAR NOT NULL,
    "Lat" DECIMAL(11,8) NULL,
    "Listed" INT NULL,
    "Location Type" VARCHAR NOT NULL,
    "Long" DECIMAL(10,8) NULL,
    "Name" VARCHAR NULL,
    "Number of Records" INT NOT NULL,
    "Region" VARCHAR NOT NULL,
    "Self Report Location" VARCHAR NULL,
    "State " VARCHAR NOT NULL,
    "StatePopName" VARCHAR NOT NULL,
    "StatePopNum" INT NOT NULL,
    "Tweet Text" VARCHAR NOT NULL,
    "Tweets" INT NOT NULL,
    "Username" VARCHAR NOT NULL,
    "profile desc" VARCHAR NULL
);
