CREATE TABLE publicbi."IUBLibrary_1" (
    "Author" VARCHAR NULL,
    "CallNumber" VARCHAR NOT NULL,
    "CallSequence" INT NOT NULL,
    "CatalogKey" INT NOT NULL,
    "ClasscodeLCSUDOCNLM" VARCHAR NOT NULL,
    "CopyNumber" INT NOT NULL,
    "DateLastCharged" DATE NOT NULL,
    "DateofPublication260c" VARCHAR NULL,
    "Format" VARCHAR NOT NULL,
    "Inactive" VARCHAR NULL,
    "ItemCreatedDate" DATE NOT NULL,
    "ItemType" VARCHAR NOT NULL,
    "Language" VARCHAR NULL,
    "LastActivityDate" DATE NOT NULL,
    "Library" VARCHAR NOT NULL,
    "MARCkey" INT NOT NULL,
    "OCLC" INT NULL,
    "PubYear" INT NOT NULL,
    "Sh" VARCHAR NOT NULL,
    "TitleControlNumber" VARCHAR NOT NULL,
    "TitleCreatedDate" DATE NOT NULL,
    "Title" VARCHAR NULL,
    "TotalCharges" INT NOT NULL,
    "Type" VARCHAR NOT NULL,
    "elvingKey" VARCHAR NOT NULL,
    "Inactive (group)" VARCHAR NOT NULL,
    "Calculation_649925789325832192" VARCHAR NOT NULL
);
