CREATE TABLE publicbi."MedPayment2_1" (
    "Number of Records" INT NOT NULL,
    "average_Medicare_allowed_amt" DOUBLE NULL,
    "average_Medicare_payment_amt" DOUBLE NULL,
    average_submitted_chrg_amt DOUBLE NULL,
    bene_day_srvc_cnt INT NULL,
    bene_unique_cnt INT NULL,
    hcpcs_code VARCHAR NULL,
    hcpcs_description VARCHAR NULL,
    line_srvc_cnt DOUBLE NULL,
    medicare_participation_indicator VARCHAR NULL,
    npi INT NOT NULL,
    nppes_credentials VARCHAR NULL,
    nppes_entity_code VARCHAR NULL,
    nppes_provider_city VARCHAR NULL,
    nppes_provider_country VARCHAR NULL,
    nppes_provider_first_name VARCHAR NULL,
    nppes_provider_gender VARCHAR NULL,
    nppes_provider_last_org_name VARCHAR NULL,
    nppes_provider_mi VARCHAR NULL,
    nppes_provider_state VARCHAR NULL,
    nppes_provider_street1 VARCHAR NULL,
    nppes_provider_street2 VARCHAR NULL,
    nppes_provider_zip INT NULL,
    place_of_service VARCHAR NULL,
    provider_type VARCHAR NULL,
    "stdev_Medicare_allowed_amt" DOUBLE NULL,
    "stdev_Medicare_payment_amt" DOUBLE NULL,
    stdev_submitted_chrg_amt DOUBLE NULL,
    "Calculation_0820513143749095" DOUBLE NULL
);
