CREATE TABLE publicbi."MLB_52" (
    "AVG" DECIMAL(16,15) NOT NULL,
    "BABIP" DECIMAL(16,15) NOT NULL,
    "FB." DECIMAL(17,16) NOT NULL,
    "GB." DECIMAL(16,15) NOT NULL,
    "ISO" DECIMAL(17,16) NOT NULL,
    "LD." DECIMAL(17,16) NOT NULL,
    "Number of Records" INT NOT NULL,
    "OBP" DECIMAL(16,15) NOT NULL,
    "OPS" DECIMAL(16,15) NOT NULL,
    "PU." DECIMAL(17,16) NOT NULL,
    "SLG" DECIMAL(16,15) NOT NULL,
    league VARCHAR NOT NULL,
    month VARCHAR NOT NULL,
    split VARCHAR NOT NULL,
    "wOBA" DECIMAL(16,15) NOT NULL,
    year INT NOT NULL
);
