CREATE TABLE publicbi."MLB_67" (
    "Number of Records" INT NOT NULL,
    atbat_des VARCHAR NULL,
    awayteam VARCHAR NOT NULL,
    b_height VARCHAR NOT NULL,
    batted_ball_type VARCHAR NOT NULL,
    batter_name VARCHAR NOT NULL,
    day INT NOT NULL,
    des VARCHAR NULL,
    event VARCHAR NULL,
    hometeam VARCHAR NOT NULL,
    inning INT NOT NULL,
    inning_side VARCHAR NOT NULL,
    league VARCHAR NOT NULL,
    level VARCHAR NOT NULL,
    month INT NOT NULL,
    "our.x" DOUBLE NOT NULL,
    "our.y" DOUBLE NOT NULL,
    p_throws VARCHAR NULL,
    pitcher_name VARCHAR NOT NULL,
    r DECIMAL(18,15) NOT NULL,
    stand VARCHAR NOT NULL,
    theta DOUBLE NOT NULL,
    year INT NOT NULL,
    "Calculation_40532458064297984" DATE NOT NULL
);
