CREATE TABLE publicbi."MulheresMil_1" (
    "Calculation_838513981443702785" VARCHAR NOT NULL,
    "Calculation_838513981462429699" VARCHAR NULL,
    "Codigo Diploma/Certificado" VARCHAR NULL,
    "Cor da Pele" VARCHAR NULL,
    "Data Diploma/Certificado" TIMESTAMP NULL,
    "Data Pré-Matricula" DATE NULL,
    "Number of Records" INT NOT NULL,
    ch_catalogo_guia VARCHAR NULL,
    ch_da_oferta INT NOT NULL,
    ch_max_financiavel INT NULL,
    ch_maxima_permitida INT NOT NULL,
    ch_min_financiavel INT NULL,
    ch_minima_do_curso INT NOT NULL,
    co_matricula_estudante INT NULL,
    cod_da_unidade_de_ensino VARCHAR NOT NULL,
    cod_ibge_da_ue INT NOT NULL,
    cod_ibge_do_local_da_oferta VARCHAR NOT NULL,
    codigo_da_oferta INT NOT NULL,
    codigo_do_curso INT NOT NULL,
    comunidade_quilombola VARCHAR NULL,
    "cpf aluno" VARCHAR NULL,
    "data de confirmacao" DATE NULL,
    "data de nascimento aluno" DATE NULL,
    data_da_publicacao DATE NULL,
    data_de_conclusao VARCHAR NULL,
    data_de_inicio DATE NULL,
    data_de_previsaode_termino DATE NULL,
    desempregado VARCHAR NULL,
    ds_email VARCHAR NULL,
    ds_identificador_turma VARCHAR NOT NULL,
    ds_tipo_beneficiario VARCHAR NULL,
    dt_cadastro VARCHAR NOT NULL,
    ead VARCHAR NOT NULL,
    edicao_catalogo_guia VARCHAR NULL,
    edital VARCHAR NULL,
    eixo_tecnologico_catalogo_guia VARCHAR NULL,
    "eixo_tecnológico" VARCHAR NOT NULL,
    "escolaridade do aluno" VARCHAR NULL,
    escolaridade_catalogo_guia VARCHAR NULL,
    forma_ingresso VARCHAR NULL,
    instituicao VARCHAR NULL,
    mantenedora VARCHAR NULL,
    municipio_da_ue VARCHAR NOT NULL,
    municipio_do_local_da_oferta VARCHAR NOT NULL,
    no_dependencia_admin VARCHAR NOT NULL,
    no_modalidade VARCHAR NULL,
    no_parceiro_demandante VARCHAR NOT NULL,
    no_programa VARCHAR NULL,
    no_sistema_ensino VARCHAR NOT NULL,
    no_subdependencia_admin VARCHAR NULL,
    "nome aluno" VARCHAR NULL,
    "nome da sit matricula (situacao detalhada)" VARCHAR NULL,
    nome_curso_catalogo_guia VARCHAR NULL,
    nome_da_ue VARCHAR NOT NULL,
    nome_da_uer VARCHAR NOT NULL,
    nome_do_curso VARCHAR NOT NULL,
    nu_telefone VARCHAR NULL,
    nu_telefone_celular VARCHAR NULL,
    oferta_cadastro_online VARCHAR NOT NULL,
    pcd VARCHAR NOT NULL,
    populacao_campo VARCHAR NULL,
    povo_indigena VARCHAR NULL,
    seguro_desenprego VARCHAR NULL,
    "sexo do aluno" VARCHAR NULL,
    situacao_da_turma VARCHAR NOT NULL,
    st_extemporaneo_matricula BOOLEAN NULL,
    st_extemporaneo_turma BOOLEAN NOT NULL,
    st_financiavel VARCHAR NOT NULL,
    subtipo_curso VARCHAR NOT NULL,
    tipo_da_oferta VARCHAR NOT NULL,
    tipo_do_local_da_oferta VARCHAR NOT NULL,
    total_conf_freq_aluno VARCHAR NULL,
    total_freq_aluno INT NULL,
    transferencia_renda VARCHAR NOT NULL,
    turno VARCHAR NOT NULL,
    uf_da_ue VARCHAR NOT NULL,
    uf_do_local_da_oferta VARCHAR NOT NULL,
    unidade_demandante VARCHAR NULL,
    vagas INT NOT NULL,
    valor_hora_aula_proposto VARCHAR NULL,
    "Calculation_838513978982854656" VARCHAR NULL
);
