CREATE TABLE publicbi."NYC_1" (
    "Address Type" VARCHAR NULL,
    "Agency Name" VARCHAR NOT NULL,
    "Agency" VARCHAR NOT NULL,
    "Borough" VARCHAR NOT NULL,
    "Bridge Highway Direction" VARCHAR NULL,
    "Bridge Highway Name" VARCHAR NULL,
    "Bridge Highway Segment" DATE NULL,
    "City" VARCHAR NULL,
    "Closed Date" TIMESTAMP NULL,
    "Community Board" VARCHAR NOT NULL,
    "Complaint Type" VARCHAR NOT NULL,
    "Created Date" TIMESTAMP NOT NULL,
    "Cross Street 1" VARCHAR NULL,
    "Cross Street 2" VARCHAR NULL,
    "Descriptor" VARCHAR NULL,
    "Due Date" TIMESTAMP NULL,
    "Facility Type" VARCHAR NULL,
    "Ferry Direction" VARCHAR NULL,
    "Ferry Terminal Name" VARCHAR NULL,
    "Garage Lot Name" VARCHAR NULL,
    "Incident Address" VARCHAR NULL,
    "Incident Zip" BIGINT NULL,
    "Intersection Street 1" VARCHAR NULL,
    "Intersection Street 2" VARCHAR NULL,
    "Landmark" VARCHAR NULL,
    "Latitude" DECIMAL(15,13) NULL,
    "Location Type" VARCHAR NULL,
    "Location" VARCHAR NULL,
    "Longitude" DECIMAL(15,13) NULL,
    "Number of Records" INT NOT NULL,
    "Park Borough" VARCHAR NOT NULL,
    "Park Facility Name" VARCHAR NOT NULL,
    "Resolution Action Updated Date" TIMESTAMP NULL,
    "Resolution Description" VARCHAR NULL,
    "Road Ramp" VARCHAR NULL,
    "School Address" VARCHAR NULL,
    "School City" VARCHAR NOT NULL,
    "School Code" VARCHAR NULL,
    "School Name" VARCHAR NOT NULL,
    "School Not Found" VARCHAR NULL,
    "School Number" VARCHAR NULL,
    "School Phone Number" VARCHAR NOT NULL,
    "School Region" VARCHAR NULL,
    "School State" VARCHAR NOT NULL,
    "School Zip" VARCHAR NOT NULL,
    "School or Citywide Complaint" VARCHAR NULL,
    "Status" VARCHAR NOT NULL,
    "Street Name" VARCHAR NULL,
    "Taxi Company Borough" VARCHAR NULL,
    "Taxi Pick Up Location" VARCHAR NULL,
    "Unique Key" INT NOT NULL,
    "Vehicle Type" VARCHAR NULL,
    "X Coordinate (State Plane)" INT NULL,
    "Y Coordinate (State Plane)" INT NULL
);
