CREATE TABLE publicbi."RealEstate1_1" (
    "Address 1" VARCHAR NULL,
    "Address 2" VARCHAR NULL,
    "County" VARCHAR NOT NULL,
    "Date of Transfer" TIMESTAMP NOT NULL,
    "District" VARCHAR NOT NULL,
    "Duration" VARCHAR NOT NULL,
    "Latitude" DECIMAL(8,6) NOT NULL,
    "Locality" VARCHAR NULL,
    "Longitude" DOUBLE NOT NULL,
    "New Build?" VARCHAR NOT NULL,
    "Number of Records" INT NOT NULL,
    "Postcode District" VARCHAR NOT NULL,
    "Postcode Region" VARCHAR NOT NULL,
    "Postcode Sector" VARCHAR NOT NULL,
    "Postcode" VARCHAR NOT NULL,
    "Price" INT NOT NULL,
    "Property Type" VARCHAR NOT NULL,
    "Street" VARCHAR NULL,
    "Town/City" VARCHAR NOT NULL,
    "Transaction ID" VARCHAR NOT NULL,
    "Month" INT NOT NULL,
    "Calculation_7270508194941839" INT NOT NULL,
    "Calculation_5960512115909696" VARCHAR NULL,
    "Calculation_5480628224156393" TIMESTAMP NULL,
    "Calculation_2630509165701334" DOUBLE NOT NULL,
    "Calculation_0390512122057182" VARCHAR NOT NULL,
    "Year" INT NOT NULL,
    "average monthly price per km2 (copy)" DOUBLE NOT NULL
);
