CREATE TABLE publicbi."RealEstate2_1" (
    "Address_1" VARCHAR NULL,
    "Address_2" VARCHAR NULL,
    "County" VARCHAR NOT NULL,
    "County (copy)" VARCHAR NOT NULL,
    "Date_of_Transfer" DATE NOT NULL,
    "District" VARCHAR NOT NULL,
    "Duration" VARCHAR NOT NULL,
    "Latitude" DECIMAL(15,13) NULL,
    "Locality" VARCHAR NULL,
    "Longitude" DOUBLE NULL,
    "New_Build" VARCHAR NOT NULL,
    "Number of Records" INT NOT NULL,
    "Postcode" VARCHAR NULL,
    "Postcode_District" VARCHAR NULL,
    "Postcode_Region" VARCHAR NULL,
    "Postcode_Sector" VARCHAR NULL,
    "Price" INT NOT NULL,
    "Price_Paid_Transaction_Type" VARCHAR NOT NULL,
    "Property_Type" VARCHAR NOT NULL,
    "Street" VARCHAR NULL,
    "Town/City" VARCHAR NOT NULL,
    "Transaction_ID" VARCHAR NOT NULL,
    "Calculation_342484700263473152" VARCHAR NOT NULL,
    "Calculation_222787466265260036" VARCHAR NOT NULL,
    "Calculation_222787466264023043" VARCHAR NOT NULL,
    "Calculation_222787466257584130" BOOLEAN NOT NULL,
    "town/city url string (copy)" VARCHAR NULL
);
