CREATE TABLE publicbi."Redfin2_2" (
    "Number of Records" INT NOT NULL,
    avg_sale_to_list DECIMAL(16,15) NULL,
    avg_sale_to_list_mom DOUBLE NULL,
    avg_sale_to_list_yoy DOUBLE NULL,
    city VARCHAR NULL,
    homes_sold INT NULL,
    homes_sold_mom DOUBLE NULL,
    homes_sold_yoy DOUBLE NULL,
    inventory INT NULL,
    inventory_mom DOUBLE NULL,
    inventory_yoy DOUBLE NULL,
    median_dom DECIMAL(5,1) NULL,
    median_dom_mom DECIMAL(5,1) NULL,
    median_dom_yoy DECIMAL(5,1) NULL,
    median_list_ppsf DOUBLE NULL,
    median_list_ppsf_mom DOUBLE NULL,
    median_list_ppsf_yoy DOUBLE NULL,
    median_list_price DOUBLE NULL,
    median_list_price_mom DOUBLE NULL,
    median_list_price_yoy DOUBLE NULL,
    median_ppsf DOUBLE NULL,
    median_ppsf_mom DOUBLE NULL,
    median_ppsf_yoy DOUBLE NULL,
    median_sale_price DOUBLE NULL,
    median_sale_price_mom DOUBLE NULL,
    median_sale_price_yoy DOUBLE NULL,
    new_listings INT NULL,
    new_listings_mom DOUBLE NULL,
    new_listings_yoy DOUBLE NULL,
    period_begin DATE NOT NULL,
    period_duration INT NOT NULL,
    period_end DATE NOT NULL,
    price_drops DOUBLE NULL,
    price_drops_mom DOUBLE NULL,
    price_drops_yoy DOUBLE NULL,
    property_type VARCHAR NOT NULL,
    region VARCHAR NOT NULL,
    region_type VARCHAR NOT NULL,
    sold_above_list DOUBLE NULL,
    sold_above_list_mom DOUBLE NULL,
    sold_above_list_yoy DOUBLE NULL,
    state VARCHAR NULL,
    state_code VARCHAR NULL,
    table_id INT NULL
);
