CREATE TABLE publicbi."Rentabilidad_9" (
    "AUTOPREVENTA: Costo Fijo" DECIMAL(18,12) NOT NULL,
    "AUTOPREVENTA: Costo Variable" DOUBLE NOT NULL,
    "AUTOPREVENTA: Costo de Devoluciones" DOUBLE NOT NULL,
    "AUTOPREVENTA: Tiempos de Venta + Traslado Autopreventa Normal" DECIMAL(18,14) NOT NULL,
    "AUTOVENTA: Carga Paseante" DOUBLE NOT NULL,
    "AUTOVENTA: Costo Fijo" DOUBLE NOT NULL,
    "AUTOVENTA: Costo Variable" DOUBLE NOT NULL,
    "AUTOVENTA: Tiempos de Venta + Traslado Autoventa Normal" DECIMAL(17,14) NOT NULL,
    "BODEGA: CEDIS Propio- Costos Bodega" DOUBLE NOT NULL,
    "BODEGA: Costo Arriendo Terceros" DOUBLE NOT NULL,
    "BODEGA: Costo Especialistas de Operaciones" VARCHAR NULL,
    "BODEGA: Distribuidores- Costos Fijos y Variables" DOUBLE NOT NULL,
    "BODEGA: Mermas" VARCHAR NULL,
    "CF" DOUBLE NOT NULL,
    "CU" DOUBLE NOT NULL,
    "Calculation_1880818214638259" DOUBLE NOT NULL,
    "Calle" VARCHAR NULL,
    "Canal de Ventas" INT NOT NULL,
    "Ciudad UO" VARCHAR NOT NULL,
    "Descripción de Canal" VARCHAR NULL,
    "Deudor NCB" INT NULL,
    "Deudor" VARCHAR NOT NULL,
    "Dias de Visita CO" VARCHAR NULL,
    "Dias de Visita TA NCB" VARCHAR NULL,
    "Dias de Visita TA" VARCHAR NULL,
    "Días de Entrega" VARCHAR NULL,
    "Días de Visita PR NCB" VARCHAR NULL,
    "Días de Visita PR" VARCHAR NULL,
    "Dïas de Entrega NCB" VARCHAR NULL,
    "Figura Especifica" VARCHAR NULL,
    "Figura" VARCHAR NOT NULL,
    "Fijo / Dinámica" VARCHAR NOT NULL,
    "Fx CO" INT NULL,
    "Fx Entrega Total NCB" INT NULL,
    "Fx Entrega Total" INT NULL,
    "Fx PR NCB" INT NULL,
    "Fx PR" INT NULL,
    "Fx TA NCB" VARCHAR NULL,
    "Fx TA" INT NULL,
    "FxED" INT NULL,
    "GEC NCB" VARCHAR NULL,
    "GEC" VARCHAR NOT NULL,
    "GERENTES VENTA: Coordinadores Bronces" DECIMAL(17,11) NOT NULL,
    "GERENTES VENTA: Costo Gerente de Ventas Normal" DECIMAL(18,11) NOT NULL,
    "GUC" VARCHAR NOT NULL,
    "Gerencia" VARCHAR NOT NULL,
    "IN" DOUBLE NOT NULL,
    "Implementación Venta" VARCHAR NOT NULL,
    "Jefatura de Reparto NCB" VARCHAR NULL,
    "Jefatura de Reparto" VARCHAR NOT NULL,
    "Jefe de Ventas NCB" VARCHAR NULL,
    "Jefe de Ventas" VARCHAR NOT NULL,
    "Latitud AUTO PREV" DECIMAL(16,14) NULL,
    "Latitud" BIGINT NULL,
    "Locación" VARCHAR NOT NULL,
    "Locación (copy)" VARCHAR NOT NULL,
    "Longitud AUTO PREV" DECIMAL(15,13) NULL,
    "Longitud" BIGINT NULL,
    "MATCH PR con NCB" VARCHAR NULL,
    "MERCADEO: Costo Refrigeración" DECIMAL(18,11) NOT NULL,
    "MERCADEO: PDE" DECIMAL(17,11) NOT NULL,
    "MERCADEO: PDV- Descuentos Habituales" INT NOT NULL,
    "MERCADEO: PDV- Descuentos No Habituales" INT NOT NULL,
    "MERCADEO: Prorrateo Mercaderistas" DOUBLE NOT NULL,
    "Modalidad de Venta" VARCHAR NOT NULL,
    "Modalidad reparto" VARCHAR NOT NULL,
    "Municipio" VARCHAR NULL,
    "NCB" VARCHAR NULL,
    "NIT" VARCHAR NULL,
    "Nombre del Cliente" VARCHAR NULL,
    "Number of Records" INT NOT NULL,
    "ON-OFF" VARCHAR NULL,
    "OP. DISTRIBUIDORES: Costo Fijo" DOUBLE NOT NULL,
    "OP. DISTRIBUIDORES: Costo Variable" DOUBLE NOT NULL,
    "OP. DISTRIBUIDORES: Filtro de Validación Costo Variable" VARCHAR NOT NULL,
    "OP. DISTRIBUIDORES: Mayoristas" DOUBLE NOT NULL,
    "OP. DISTRIBUIDORES: NO GVF" DOUBLE NOT NULL,
    "OP. DISTRIBUIDORES: Prorrateo Visitas" DOUBLE NOT NULL,
    "OTROS VENTA: Costo de Rotación Pre/Televendedores" DECIMAL(16,12) NULL,
    "PREVENTA NCB: Costo de Prevendedor NCB" DOUBLE NULL,
    "PREVENTA NCB: Tiempos de Venta + Traslado Preventa NCB" DECIMAL(16,14) NULL,
    "PREVENTA: Costo de Prevendedor Normal" DOUBLE NOT NULL,
    "PREVENTA: Tiempos de Venta + Traslado Preventa Normal" DECIMAL(17,14) NOT NULL,
    "Población Distribuidor GVF/GVI" VARCHAR NOT NULL,
    "Precio Prom. CF" DOUBLE NOT NULL,
    "Precio Prom. CU" DOUBLE NOT NULL,
    "REPARTO: Costo Supervisores" DOUBLE NOT NULL,
    "REPARTO: Costo de Bodegas Secundarias" DOUBLE NOT NULL,
    "REPARTO: Costo de Depreciación" DOUBLE NOT NULL,
    "REPARTO: Costo de Mantenimiento" DOUBLE NOT NULL,
    "REPARTO: Devoluciones" DOUBLE NOT NULL,
    "REPARTO: Merma de Ruta" DOUBLE NOT NULL,
    "REPARTO: Rutas Dinamicas- Costos Fijos" DOUBLE NOT NULL,
    "REPARTO: Rutas Dinamicas- Costos Variables" DOUBLE NOT NULL,
    "REPARTO: Rutas Fijas- Costos Fijos" DOUBLE NOT NULL,
    "REPARTO: Rutas Fijas- Costos Variables" DOUBLE NOT NULL,
    "REPARTO: Tiempos de Reparto Fijo + Variable" DECIMAL(18,13) NOT NULL,
    "REPARTO: Visitas de Reparto Acumulado Ene-May" INT NOT NULL,
    "Razón Social" VARCHAR NULL,
    "Rentabilidad" DOUBLE NOT NULL,
    "Ruta CO" VARCHAR NULL,
    "Ruta ED" VARCHAR NULL,
    "Ruta PR NCB" VARCHAR NULL,
    "Ruta PR" VARCHAR NULL,
    "Ruta TA NCB" VARCHAR NULL,
    "Ruta TA" VARCHAR NULL,
    "Ruta de Reparto NCB" VARCHAR NULL,
    "Ruta de Reparto" VARCHAR NOT NULL,
    "Ruta de Venta NCB" VARCHAR NULL,
    "Ruta de Venta" VARCHAR NOT NULL,
    "Sede Foraneo Sintec" VARCHAR NOT NULL,
    "Sede/Foráneo" VARCHAR NOT NULL,
    "T1: Cedis Propio" DOUBLE NOT NULL,
    "T1: Distruidor Tercero" DOUBLE NOT NULL,
    "TELEVENTA OFIC: Costo Televendedor Normal" VARCHAR NULL,
    "TELEVENTA OFIC: Tiempos de Venta" VARCHAR NULL,
    "TELEVENTA: Costo Televendedor NCB" INT NULL,
    "TELEVENTA: Costo de Televendedor Normal" DOUBLE NOT NULL,
    "TELEVENTA: Tiempos de Venta Televenta NCB" INT NULL,
    "TELEVENTA: Tiempos de Venta Televenta Normal" DECIMAL(16,14) NOT NULL,
    "TOTAL BODEGA C/ARRIENDOS" DOUBLE NOT NULL,
    "TOTAL MERCADEO" DOUBLE NOT NULL,
    "TOTAL REPARTO" DOUBLE NOT NULL,
    "TOTAL T1" DOUBLE NOT NULL,
    "TOTAL VENTA" DOUBLE NOT NULL,
    "Total CdS" DOUBLE NOT NULL,
    "Tradicional/ Moderno" VARCHAR NOT NULL,
    "UO" VARCHAR NOT NULL,
    "Util. Bruta" DOUBLE NOT NULL,
    "VENTA:  MERMA DE VENTA" DOUBLE NOT NULL,
    "VENTA: Coord, OL, Merc. 14" INT NOT NULL,
    "VENTA: Costo Renta Equipo Televenta NCB" INT NULL,
    "VENTA: Costo Renta de Equipo Televenta Normal" DECIMAL(18,12) NOT NULL,
    "VENTA: Costo Total Mercaderistas" DECIMAL(15,11) NOT NULL,
    "VENTA: Costo de Handheld Rutas Autoventa" DOUBLE NOT NULL,
    "VENTA: Costo de Handheld Rutas NCBs" DECIMAL(15,11) NULL,
    "VENTA: Costo de Handheld Rutas Preventa" DOUBLE NOT NULL,
    "VENTA: Costos EDI" DECIMAL(16,10) NOT NULL,
    "VENTA: Descuentos Lista de Precios" INT NOT NULL,
    "Zona" VARCHAR NOT NULL,
    "GEC (group)" VARCHAR NOT NULL
);
