CREATE TABLE publicbi."SalariesFrance_2" (
    "APPELLATION" VARCHAR NOT NULL,
    "CODES_ROME_DESTINATION" VARCHAR NOT NULL,
    "Codes Rome Destination (copie)" VARCHAR NOT NULL,
    "CODES_ROME_ORIGINE" VARCHAR NOT NULL,
    "Calculation_9301203172454540" INT NOT NULL,
    "DESCRIPTION" VARCHAR NOT NULL,
    "ID_TYPES_MOBILITE" DECIMAL(1,0) NOT NULL,
    "Number of Records" INT NOT NULL,
    "ROME_LIB_DESTINATION" VARCHAR NOT NULL,
    "ROME_LIB_ORIGINE" VARCHAR NOT NULL,
    "TYPES_MOBILITE" VARCHAR NOT NULL
);
