CREATE TABLE publicbi."TableroSistemaPenal_6" (
    "AUDIENCIA" VARCHAR NOT NULL,
    "AÑO CAUSA" INT NOT NULL,
    "COD_MATERIA" INT NOT NULL,
    "COD_TRIB" INT NOT NULL,
    "CORTE" VARCHAR NOT NULL,
    "DELITO" VARCHAR NULL,
    "FECHA AUDIENCIA" TIMESTAMP NOT NULL,
    "Number of Records" INT NOT NULL,
    "PAÍS" VARCHAR NOT NULL,
    "RIT" INT NOT NULL,
    "TIP TRIB" VARCHAR NOT NULL,
    "TIPO" INT NOT NULL,
    "TRIBUNAL" VARCHAR NOT NULL
);
