CREATE TABLE publicbi."TableroSistemaPenal_2" (
    "AGRUPADOR" VARCHAR NOT NULL,
    "AÑO" INT NOT NULL,
    "Año Ingreso" VARCHAR NOT NULL,
    "COD_FORMAINICIO" INT NOT NULL,
    "CRR_IDCAUSA" INT NOT NULL,
    "Calculation_6580723191504157" VARCHAR NOT NULL,
    "Cod Materia" INT NOT NULL,
    "Cod. Corte" INT NOT NULL,
    "Cod. Tribunal" INT NOT NULL,
    "Corte" VARCHAR NOT NULL,
    "Fecha Ingreso Delito" VARCHAR NOT NULL,
    "Fecha Ingreso" VARCHAR NOT NULL,
    "Forma Inicio" VARCHAR NOT NULL,
    "Materia" VARCHAR NOT NULL,
    "Mes Ingreso" VARCHAR NOT NULL,
    "Number of Records" INT NOT NULL,
    "RIT" INT NOT NULL,
    "Región" VARCHAR NOT NULL,
    "TIP_TRIB" VARCHAR NOT NULL,
    "Tipo" VARCHAR NOT NULL,
    "Tribunal" VARCHAR NOT NULL,
    "Materia (group)" VARCHAR NOT NULL
);
