CREATE TABLE publicbi."TrainsUK1_4" (
    "Average Lateness" DOUBLE NOT NULL,
    "Calculation_2040623161253421" DECIMAL(4,2) NOT NULL,
    "Calculation_2890421151640665" VARCHAR NOT NULL,
    "Calculation_3330422103625946" DECIMAL(17,16) NOT NULL,
    "Engineering Allowance (mins)" INT NULL,
    "Headcode" VARCHAR NOT NULL,
    "Median Lateness" DECIMAL(4,2) NOT NULL,
    "Operator Name" VARCHAR NOT NULL,
    "Operator" VARCHAR NOT NULL,
    "Pathing Allowance (mins)" DECIMAL(3,1) NOT NULL,
    "Performance Allowance (mins)" DECIMAL(2,1) NOT NULL,
    "Planned Dest Location Full Name" VARCHAR NOT NULL,
    "Planned Origin Location Full Name" VARCHAR NOT NULL,
    "Punctuality Threshold" INT NOT NULL,
    "RT%" DECIMAL(18,17) NOT NULL,
    "Ranking" INT NULL,
    "Section Start Location Full Name" VARCHAR NOT NULL,
    "Section Start Location Name" VARCHAR NOT NULL,
    "Time-to-10%" DECIMAL(17,16) NOT NULL,
    "Time-to-2%" DECIMAL(18,17) NOT NULL,
    "Time-to-5%" DECIMAL(17,16) NOT NULL,
    "Timetable" VARCHAR NOT NULL,
    "Train Count" INT NOT NULL,
    "v_Headcode Description" VARCHAR NOT NULL,
    "v_Section_WTT_Time" TIME NOT NULL,
    "v_WTT and Section Name and Timing Event" VARCHAR NOT NULL,
    "Calculation_2480421151322357" VARCHAR NOT NULL,
    "Calculation_0430624152715434" VARCHAR NOT NULL
);
