CREATE TABLE publicbi."TrainsUK2_2" (
    "Actual Total Distance Miles" DECIMAL(5,2) NULL,
    "Date" TIMESTAMP NULL,
    "Financial Year & Period" VARCHAR NULL,
    "Number of Records" INT NOT NULL,
    "Operator" VARCHAR NULL,
    "Planned Dest Actual Datetime" TIMESTAMP NULL,
    "Planned Dest GBTT Datetime" TIMESTAMP NULL,
    "Planned Dest Stanox Description" VARCHAR NULL,
    "Planned Dest Stanox" INT NULL,
    "Planned Dest WTT Datetime" TIMESTAMP NULL,
    "Planned Orig Stanox Description" VARCHAR NULL,
    "Planned Orig Stanox" INT NULL,
    "Planned Origin Actual Datetime" TIMESTAMP NULL,
    "Planned Origin GBTT Datetime" TIMESTAMP NULL,
    "Planned Origin WTT Datetime" TIMESTAMP NULL,
    "Planned Total Distance Miles" DECIMAL(5,2) NULL,
    "Service Group Code" VARCHAR NULL,
    "Service Group Description" VARCHAR NULL,
    "TSC" INT NULL,
    "Train ID" VARCHAR NULL,
    "v_CaSL Flag" INT NOT NULL,
    "v_Dest Lateness (GBTT)" INT NULL,
    "v_Dest Lateness (WTT)" DECIMAL(4,1) NULL,
    "v_Full Cancellation Flag" INT NOT NULL,
    "v_Origin Lateness (GBTT)" INT NULL,
    "v_Origin Lateness (WTT)" INT NULL,
    "v_PPM Pass Flag" INT NOT NULL,
    "v_RT Flag" INT NOT NULL,
    "v_Sector" VARCHAR NULL,
    "v_Unique Train ID" VARCHAR NULL,
    "c_Origin Time (GBTT) (copy)" VARCHAR NULL,
    "Calculation_2510610113130467" INT NULL,
    "Calculation_4220604162631191" VARCHAR NULL,
    "Calculation_5580608170646388" VARCHAR NULL,
    "Calculation_6080608165132814" VARCHAR NULL,
    "Calculation_9230610113105724" INT NULL,
    "Date (group)" TIMESTAMP NULL
);
